[project]
name = "cryptpass-rust"
version = "0.0.0" # Actual version is tracked in Cargo.toml
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.4.0",
    "ansible-lint>=25.2.1",
    "git-filter-repo>=2.47.0",
]
